# fly.toml app configuration file
# Gerado para o projeto Django com SQLite

app = "back-x-project"
primary_region = "gru"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  # Agora executa migrações e coleta arquivos estáticos corretamente
  release_command = "poetry run python manage.py migrate"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

# MONTANDO VOLUME PARA BANCO DE DADOS (SQLite)
[mounts]
  source = "db_data"
  destination = "/code/db"
