app = "back-x-project"
primary_region = "gru"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"
  DATABASE_URL = "postgres://postgres:jscVJXSeSdSWLPl@x-copia-api.flycast:5432/postgres"
  SECRET_KEY = "6szHqlxJAJ1QcaPfCc56Dd1AcOIWEtWoHsoPmnGOj65ILWPDI7"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "poetry run python manage.py migrate"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
